couche2.c
int compute_nstripe(virtual_disk_t *r5Disk, int nblocks)
Retourne le nombre de bandes necessaires pour écrire n blocs.
Nombre de blocs (int) Nombre de bandes (int)
References virtual_disk_s::ndisk.
Referenced by write_chunk, read_inodes_table.
block_t compute_parity(virtual_disk_t *r5, stripe_t *tocompute, int indice_parite)
Calcule le bloc de parité d'une stripe.
virtual_disk_t *, stripe_t *,int block_t
References stripe_s::stripe, stripe_s::nblocks, xorbl.
Referenced by write_chunk.
int compute_parity_index(virtual_disk_t *r5, int numbd)
Calcule la position du block de parité d'une stripe.
virtual_disk_t , int numero de la bande dans la liste du raid int
References virtual_disk_s::ndisk.
Referenced by write_chunk, read_chunk, write_inodes_table.
void write_stripe(virtual_disk_t *r5, stripe_t *ecrire, uint pos)
Ecrit une stripe a la position passée en argument sur le raid passé en argument.
virtual_disk_t ,stripe_t ,int void
References virtual_disk_s::ndisk, write_block, stripe_s::stripe.
Referenced by write_chunk.
stripe_t* init_bande(virtual_disk_t *r5)
References stripe_s::nblocks, virtual_disk_s::ndisk, stripe_s::stripe.
Referenced by write_chunk, read_inodes_table.
void delete_bande(stripe_t **bande)
Libere la mémoir réservée par une bande.
stripe_t * void
Referenced by write_chunk, read_inodes_table.
void print_stripe(virtual_disk_t *r5, stripe_t *stripe)
Affiche une bande.
virtual_disk_t ,stripe_t void
References BLOCK_SIZE, virtual_disk_s::ndisk, stripe_s::stripe, octetsToHexa.
void write_chunk(virtual_disk_t *r5, char *buffer, int n, uint startBlock)
Ecrit une stripe a la position passée en argument sur le raid passé en argument.
virtual_disk_t ,stripe_t ,int void
References compute_nblock, compute_nstripe, BLOCK_SIZE, block_s::data, init_bande, compute_parity_index, virtual_disk_s::ndisk, stripe_s::stripe, compute_parity, write_stripe, delete_bande.
Referenced by cmd_test1, write_inodes_table, write_super_block.
int afficher_raid_hexa(virtual_disk_t *r5)
References virtual_disk_s::ndisk, affichageBlockHexa.
Referenced by cmd_test1, cmd_test2.
int afficher_raid_decimal(virtual_disk_t *r5)
affiche les disques du raid en valeurs décimales
virtual_disk_t * int
References virtual_disk_s::ndisk, affichageBlockDecimal.
Referenced by cmd_test1.
void cmd_test1(virtual_disk_t *r5)
fonction de test pour write_chunk
virtual_disk_t *
References afficher_raid_decimal, write_chunk, afficher_raid_hexa.
Referenced by couche2.
int read_stripe(virtual_disk_t *r5, stripe_t *lire, uint pos)
Lis une bande a partir de la position passée en parametre.
virtual_disk_t *,stripe_t *, uint int
References virtual_disk_s::ndisk, read_block, stripe_s::stripe.
Referenced by read_super_block, read_inodes_table.
void cmd_test2(virtual_disk_t *r5)
Fonction de test pour read_chunk.
virtual_disk_t * void
References afficher_raid_hexa, read_chunk, turn_off_disk_raid5.
Referenced by couche2.
int compute_num_bande(virtual_disk_t *r5, int nbloc)
Fonction retournant le num de la bande actuelle.
virtual_disk_t * le systeme int le numéro du block actuel : int le numero de la bande
References virtual_disk_s::ndisk.
Referenced by read_chunk.
char* read_chunk(virtual_disk_t *r5, uint start_block, int n)
Fonction de lecture de tableau de char.
virtual_disk_t * , uint , int char *
References compute_nblock, virtual_disk_s::ndisk, compute_parity_index, compute_num_bande, read_block, BLOCK_SIZE, block_s::data.
Referenced by cmd_test2.
int couche2(void)
References init_disk_raid5, cmd_test1, cmd_test2.