couche1.h
void add_finChemin(const char *repertoire, char *nomDisque, size_t lengthRep)
Copie la chaine "repertoire" dans nomDisque en y ajoutant "/d0\0".
chaine de char (repertoire) chaine de char (disk) size_t void
Referenced by init_disk_raid5.
void init_disk_raid5(const char *repertoire, virtual_disk_t *r5Disk)
Initialise la variable globale r5Disk.
chaine de char (repertoire cible) virtual_disk_t void
References add_finChemin, virtual_disk_s::ndisk, virtual_disk_s::raidmode, CINQ, virtual_disk_s::storage.
Referenced by couche1, couche2, main.
void turn_off_disk_raid5(virtual_disk_t *r5Disk)
Ferme les fichiers ouverts et sauvegarde le super block?
chaine de char (repertoire cible) virtual_disk_t void
References virtual_disk_s::ndisk, virtual_disk_s::storage.
Referenced by couche1, cmd_test2.
void info_disque(virtual_disk_t *r5Disk)
Affiche des infos sur les disques ouverts.
virtual_disk_t : void
References virtual_disk_s::ndisk.
Referenced by couche1.
int compute_nblock(int n)
calcule le nombre de blocs pour coder "n" octets
integer integer
Referenced by write_chunk, read_chunk, write_inodes_table, init_inode.
void write_block(virtual_disk_t *RAID5, block_t *entrant, uint pos, int idDisk)
Ecrit un bloc à la position pos sur le disque.
virtual_disk_t block_t (à ecrire) uint (position à laquelle on ecrit) integer (n° disk) void
References virtual_disk_s::storage, block_s::data, BLOCK_SIZE.
Referenced by couche1, write_stripe.
int read_block(virtual_disk_t *RAID5, block_t *recup, uint pos, int idDisk)
Lit un bloc à la position pos sur le disque.
virtual_disk_t block_t (à lire) uint (position à laquelle on lit) integer (n° disk) integer
References virtual_disk_s::storage, block_s::data.
Referenced by block_repair, affichageBlockHexa, affichageBlockDecimal, couche1, read_stripe, read_chunk.
void block_repair(virtual_disk_t *RAID5, uint pos, int idDisk)
References virtual_disk_s::ndisk, read_block, xorbl.
void octetsToHexa(block_t monBloc, char *nbHexa)
prend un tableau de 4 octets (char) et le transforme en Hexadecimal assert(monBloc[i]<256);
block_t (Contient le tableau de bits) char* (Caractere dans lequel on met l'hexa) : void
References BLOCK_SIZE, block_s::data, conversionHexa.
Referenced by affichageBlockHexa, affichageBlockDecimal, couche1, print_stripe.
int affichageBlockHexa(virtual_disk_t *RAID5, int idDisk, uint pos, FILE *output)
affiche un bloc de donnees en hexadecimal
virtual_disk_t integer (n° disk) integer (posit° de ce qu'on veut afficher) : void
References BLOCK_SIZE, read_block, octetsToHexa.
Referenced by affichageDisque, afficher_raid_hexa.
int affichageBlockDecimal(virtual_disk_t *RAID5, int idDisk, uint pos, FILE *output)
References BLOCK_SIZE, read_block, octetsToHexa, conversionDec.
Referenced by afficher_raid_decimal.
char conversionHexa(char nb4bits)
transforme un nombre en son chiffre en hexa
nb4bits, la valeur de 4 bits en entier : le chiffre en hexadecimal
Referenced by octetsToHexa.
void xorbl(block_t *xa, block_t *xb, block_t *destination)
References BLOCK_SIZE, block_s::data.
Referenced by block_repair, compute_parity.
int couche1(void)
References r5Disk, init_disk_raid5, info_disque, block_s::data, write_block, read_block, octetsToHexa, affichageDisque, turn_off_disk_raid5.
void affichageDisque(virtual_disk_t *RAID5, int idDisk, FILE *output)
References affichageBlockHexa.
Referenced by couche1.
int conversionDec(int nb4bits)
Referenced by affichageBlockDecimal.