couche3.c
void read_super_block(virtual_disk_t *r5Disk, super_block_t *superblock)
Lecture du superbloc.
virtual_disk_t , super_block_t void
References SUPER_BLOCK_SIZE, BLOCK_SIZE, read_stripe, virtual_disk_s::ndisk, super_block_s::raid_type, super_block_s::nb_blocks_used, super_block_s::first_free_byte.
void read_inodes_table(virtual_disk_t *r5Disk, inode_table_t *table)
Lecture de la table d'inodes.
virtual_disk_t ,inode_table_t : void
References compute_nstripe, INODE_SIZE, FILENAME_MAX_SIZE, init_bande, INODE_TABLE_SIZE, read_stripe, virtual_disk_s::ndisk, BLOCK_SIZE, delete_bande.
Referenced by cmd_dump_inode, write_super_block.
void write_inodes_table(virtual_disk_t *r5Disk, inode_table_t inode)
Ecriture de la table d'inodes.
virtual_disk_t ,inode_table_t : void
References INODE_TABLE_SIZE, BLOCK_SIZE, compute_nblock, virtual_disk_s::ndisk, compute_parity_index, FILENAME_MAX_SIZE, write_chunk.
Referenced by main.
void delete_inode(virtual_disk_t *r5Disk, int numInode)
Supression d'inode.
virtual_disk_t void
References virtual_disk_s::number_of_files, virtual_disk_s::inodes.
int get_nb_files(inode_table_t tab)
Retourne le nombre de fichiers dans la table d'inodes.
inode_table_t Nombre de fichiers (int)
References get_unused_inodes.
Referenced by cmd_dump_inode.
int get_unused_inodes(inode_table_t tab)
Retourne le nombre de fichiers inutilisés dans la table d'inodes.
inode_table_t Nombre de fichiers (int)
References INODE_TABLE_SIZE.
Referenced by get_nb_files, write_super_block, first_free_byte.
inode_t init_inode(char nomFichier[FILENAME_MAX_SIZE], uint taille, uint start)
Initialisation d'une inode.
nom_de_fichier (char *),taille (uint),debut (uint) inode_t
References inode_s::filename, inode_s::size, inode_s::nblock, compute_nblock, inode_s::first_byte.
void cmd_dump_inode(char *nomRep, virtual_disk_t *r5Disk)
References read_inodes_table, virtual_disk_s::number_of_files, get_nb_files, virtual_disk_s::inodes.
Referenced by main.
void write_super_block(virtual_disk_t *r5Disk)
Ecriture du superbloc.
virtual_disk_t void
References read_inodes_table, virtual_disk_s::inodes, virtual_disk_s::super_block, super_block_s::nb_blocks_used, get_unused_inodes, super_block_s::first_free_byte, super_block_s::raid_type, virtual_disk_s::raidmode, write_chunk.
void first_free_byte(virtual_disk_t *r5Disk)
Ecriture de la position du premier octet libre dans le r5Disk.
virtual_disk_t void
References get_unused_inodes, virtual_disk_s::inodes, virtual_disk_s::super_block, super_block_s::first_free_byte.
void main()
References INODE_TABLE_SIZE, inode_s::first_byte, init_disk_raid5, write_inodes_table, cmd_dump_inode.