.TH "cmd_format.c" 3 "Mon Apr 1 2019" "PROJET_S4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd_format.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBformat\fP (char *dirname, int size, int diskid)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void format (char * dirname, int size, int diskid)"

.PP
Definition at line 10 of file cmd_format\&.c\&.
.SS "int main (int argc, char ** argv)"
command nom_repertoire nb_disks taille_fichier (octets) 
.PP
Definition at line 24 of file cmd_format\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PROJET_S4 from the source code\&.
