.TH "inode_s" 3 "Mon Apr 1 2019" "PROJET_S4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inode_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <raid_defines\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBfilename\fP [\fBFILENAME_MAX_SIZE\fP]"
.br
.ti -1c
.RI "\fBuint\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBuint\fP \fBnblock\fP"
.br
.ti -1c
.RI "\fBuint\fP \fBfirst_byte\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file raid_defines\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char filename[\fBFILENAME_MAX_SIZE\fP]"

.PP
Definition at line 29 of file raid_defines\&.h\&.
.SS "\fBuint\fP first_byte"

.PP
Definition at line 32 of file raid_defines\&.h\&.
.SS "\fBuint\fP nblock"

.PP
Definition at line 31 of file raid_defines\&.h\&.
.SS "\fBuint\fP size"

.PP
Definition at line 30 of file raid_defines\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJET_S4 from the source code\&.
