.TH "raid_defines.h" 3 "Mon Apr 1 2019" "PROJET_S4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
raid_defines.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBblock_s\fP"
.br
.ti -1c
.RI "struct \fBinode_s\fP"
.br
.ti -1c
.RI "struct \fBsuper_block_s\fP"
.br
.ti -1c
.RI "struct \fBvirtual_disk_s\fP"
.br
.ti -1c
.RI "struct \fBstripe_s\fP"
.br
.ti -1c
.RI "struct \fBfile_s\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBERREUR\fP   \-1"
.br
.ti -1c
.RI "#define \fBBLOCK_SIZE\fP   4"
.br
.ti -1c
.RI "#define \fBFILENAME_MAX_SIZE\fP   32"
.br
.ti -1c
.RI "#define \fBMAX_FILE_SIZE\fP   (50*1024)"
.br
.ti -1c
.RI "#define \fBINODE_TABLE_SIZE\fP   10"
.br
.ti -1c
.RI "#define \fBMAX_MSG\fP   1024"
.br
.ti -1c
.RI "#define \fBSUPER_BLOCK_SIZE\fP   4"
.br
.ti -1c
.RI "#define \fBINODES_START\fP   \fBSUPER_BLOCK_SIZE\fP*\fBBLOCK_SIZE\fP+1"
.br
.ti -1c
.RI "#define \fBINODE_SIZE\fP   11"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBuint\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuchar\fP"
.br
.ti -1c
.RI "typedef struct \fBblock_s\fP \fBblock_t\fP"
.br
.ti -1c
.RI "typedef struct \fBinode_s\fP \fBinode_t\fP"
.br
.ti -1c
.RI "typedef \fBinode_t\fP \fBinode_table_t\fP[\fBINODE_TABLE_SIZE\fP]"
.br
.ti -1c
.RI "typedef struct \fBsuper_block_s\fP \fBsuper_block_t\fP"
.br
.ti -1c
.RI "typedef struct \fBvirtual_disk_s\fP \fBvirtual_disk_t\fP"
.br
.ti -1c
.RI "typedef struct \fBstripe_s\fP \fBstripe_t\fP"
.br
.ti -1c
.RI "typedef struct \fBfile_s\fP \fBfile_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBraid\fP { \fBZERO\fP, \fBUN\fP, \fBCINQ\fP, \fBZERO_UN\fP, \fBUN_ZERO\fP, \fBCINQUANTE\fP, \fBCENT\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BLOCK_SIZE   4"

.PP
Definition at line 7 of file raid_defines\&.h\&.
.SS "#define ERREUR   \-1"

.PP
Definition at line 6 of file raid_defines\&.h\&.
.SS "#define FILENAME_MAX_SIZE   32"

.PP
Definition at line 8 of file raid_defines\&.h\&.
.SS "#define INODE_SIZE   11"

.PP
Definition at line 14 of file raid_defines\&.h\&.
.SS "#define INODE_TABLE_SIZE   10"

.PP
Definition at line 10 of file raid_defines\&.h\&.
.SS "#define INODES_START   \fBSUPER_BLOCK_SIZE\fP*\fBBLOCK_SIZE\fP+1"

.PP
Definition at line 13 of file raid_defines\&.h\&.
.SS "#define MAX_FILE_SIZE   (50*1024)"

.PP
Definition at line 9 of file raid_defines\&.h\&.
.SS "#define MAX_MSG   1024"

.PP
Definition at line 11 of file raid_defines\&.h\&.
.SS "#define SUPER_BLOCK_SIZE   4"

.PP
Definition at line 12 of file raid_defines\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBblock_s\fP  \fBblock_t\fP"

.SS "typedef struct \fBfile_s\fP  \fBfile_t\fP"

.SS "typedef struct \fBinode_s\fP  \fBinode_t\fP"

.SS "typedef \fBinode_t\fP inode_table_t[\fBINODE_TABLE_SIZE\fP]"

.PP
Definition at line 37 of file raid_defines\&.h\&.
.SS "typedef struct \fBstripe_s\fP  \fBstripe_t\fP"

.SS "typedef struct \fBsuper_block_s\fP  \fBsuper_block_t\fP"

.SS "typedef unsigned char \fBuchar\fP"

.PP
Definition at line 17 of file raid_defines\&.h\&.
.SS "typedef unsigned int \fBuint\fP"

.PP
Definition at line 16 of file raid_defines\&.h\&.
.SS "typedef struct \fBvirtual_disk_s\fP  \fBvirtual_disk_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBraid\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIZERO \fP\fP
.TP
\fB\fIUN \fP\fP
.TP
\fB\fICINQ \fP\fP
.TP
\fB\fIZERO_UN \fP\fP
.TP
\fB\fIUN_ZERO \fP\fP
.TP
\fB\fICINQUANTE \fP\fP
.TP
\fB\fICENT \fP\fP
.PP
Definition at line 18 of file raid_defines\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for PROJET_S4 from the source code\&.
