.TH "stripe_s" 3 "Mon Apr 1 2019" "PROJET_S4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stripe_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <raid_defines\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnblocks\fP"
.br
.ti -1c
.RI "\fBblock_t\fP * \fBstripe\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file raid_defines\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int nblocks"

.PP
Definition at line 58 of file raid_defines\&.h\&.
.SS "\fBblock_t\fP* stripe"

.PP
Definition at line 59 of file raid_defines\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJET_S4 from the source code\&.
