.TH "super_block_s" 3 "Mon Apr 1 2019" "PROJET_S4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
super_block_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <raid_defines\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBraid\fP \fBraid_type\fP"
.br
.ti -1c
.RI "\fBuint\fP \fBnb_blocks_used\fP"
.br
.ti -1c
.RI "\fBuint\fP \fBfirst_free_byte\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file raid_defines\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBuint\fP first_free_byte"

.PP
Definition at line 42 of file raid_defines\&.h\&.
.SS "\fBuint\fP nb_blocks_used"

.PP
Definition at line 41 of file raid_defines\&.h\&.
.SS "enum \fBraid\fP raid_type"

.PP
Definition at line 40 of file raid_defines\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJET_S4 from the source code\&.
