.TH "virtual_disk_s" 3 "Mon Apr 1 2019" "PROJET_S4" \" -*- nroff -*-
.ad l
.nh
.SH NAME
virtual_disk_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <raid_defines\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumber_of_files\fP"
.br
.ti -1c
.RI "\fBsuper_block_t\fP \fBsuper_block\fP"
.br
.ti -1c
.RI "\fBinode_table_t\fP \fBinodes\fP"
.br
.ti -1c
.RI "int \fBndisk\fP"
.br
.ti -1c
.RI "enum \fBraid\fP \fBraidmode\fP"
.br
.ti -1c
.RI "FILE ** \fBstorage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file raid_defines\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBinode_table_t\fP inodes"

.PP
Definition at line 49 of file raid_defines\&.h\&.
.SS "int ndisk"

.PP
Definition at line 50 of file raid_defines\&.h\&.
.SS "int number_of_files"

.PP
Definition at line 47 of file raid_defines\&.h\&.
.SS "enum \fBraid\fP raidmode"

.PP
Definition at line 51 of file raid_defines\&.h\&.
.SS "FILE** storage"

.PP
Definition at line 52 of file raid_defines\&.h\&.
.SS "\fBsuper_block_t\fP super_block"

.PP
Definition at line 48 of file raid_defines\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for PROJET_S4 from the source code\&.
